- name: Configure server
  hosts: localhost
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name:
        - nginx
        state: present
    -
    - name: Configure virtual environment
      ansible.builtin.pip:
          requirements: /flask-app/app/requirements.txt
          virtualenv: /flask-app/venv
    - name: create app services
      ansible.builtin.template:
        src: template/app.service.j2
        dest: /etc/systemd/system/app.service
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Reload systemd and start the app.
      ansible.builtin.systemd:
        state: restarted
        name: app
        daemon_reload: yes

    - name: Configure nginx
      ansible.builtin.template:
        src: template/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled
        state: directory
        mode: '0755'

    - name: Configure nginx sites-enabled
      ansible.builtin.template:
        src: template/default
        dest: /etc/nginx/sites-enabled/default
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Restarted nginx.
      ansible.builtin.systemd:
        state: restarted
        name: nginx
